/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CuratorOrganization.TrainingManagerRole;

import Business.EcoSystem;
import Business.Enterpise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Organization.TrainingProcessOrganization;
import Business.Organization.TrainingRequestManagerOrganization;
import Business.Questionnaire.FamilyBackgroundQuestionaire;
import Business.Questionnaire.Questionnaire;
import Business.Questionnaire.TrainingQuestionaire;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.TrainingRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author sanch
 */
public class AddTrainingRequestDetailsJPanel extends javax.swing.JPanel {
private JPanel userProcessContainer;
    private TrainingRequestManagerOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    EcoSystem business;
    TrainingRequest request;
    /**
     * Creates new form ManageTraining
     */
    public AddTrainingRequestDetailsJPanel(JPanel userProcessContainer, UserAccount userAccount, TrainingRequestManagerOrganization organization, Enterprise enterprise, EcoSystem business,TrainingRequest workrequest) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization =(TrainingRequestManagerOrganization) organization;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        this.business = business;
        this.request = workrequest;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        trainingCombo = new javax.swing.ButtonGroup();
        disabilityCombo = new javax.swing.ButtonGroup();
        specificCombo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnRequestJob = new javax.swing.JButton();
        backJBtn = new javax.swing.JButton();
        jTabbedPane = new javax.swing.JTabbedPane();
        jobPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        receivedTrainingNo = new javax.swing.JRadioButton();
        receivedTrainingYes = new javax.swing.JRadioButton();
        skillLabel = new javax.swing.JLabel();
        trainingType = new javax.swing.JComboBox<>();
        educationPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        disabilityNo = new javax.swing.JRadioButton();
        disabilityYes = new javax.swing.JRadioButton();
        disableLabel = new javax.swing.JLabel();
        disabilityType = new javax.swing.JComboBox<>();
        familyBackPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jChkNuclear = new javax.swing.JCheckBox();
        chkSibHld = new javax.swing.JCheckBox();
        chkSingleParent = new javax.swing.JCheckBox();
        chkExtended = new javax.swing.JCheckBox();
        criminalPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        trainingDurationCombo = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        specificComboYes = new javax.swing.JRadioButton();
        specificComboNo = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        seekLabel = new javax.swing.JLabel();
        trainingInterestCombo = new javax.swing.JComboBox<>();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Enter Individual job Details");

        btnRequestJob.setBackground(new java.awt.Color(51, 255, 51));
        btnRequestJob.setText("Request Job");
        btnRequestJob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestJobActionPerformed(evt);
            }
        });

        backJBtn.setBackground(new java.awt.Color(255, 51, 51));
        backJBtn.setText("<< Back");
        backJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJBtnActionPerformed(evt);
            }
        });

        jobPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Have you ever received any specific skill training ?");

        trainingCombo.add(receivedTrainingNo);
        receivedTrainingNo.setText("No");
        receivedTrainingNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receivedTrainingNoActionPerformed(evt);
            }
        });

        trainingCombo.add(receivedTrainingYes);
        receivedTrainingYes.setText("Yes");
        receivedTrainingYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receivedTrainingYesActionPerformed(evt);
            }
        });

        skillLabel.setText("In which field have you received training ?");
        skillLabel.setEnabled(false);

        trainingType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Physical Labor", "Carpentry", "Mechanic", "Security", "Construction", "Cleaning", "Other" }));
        trainingType.setEnabled(false);

        javax.swing.GroupLayout jobPanelLayout = new javax.swing.GroupLayout(jobPanel);
        jobPanel.setLayout(jobPanelLayout);
        jobPanelLayout.setHorizontalGroup(
            jobPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jobPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jobPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(trainingType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jobPanelLayout.createSequentialGroup()
                        .addComponent(receivedTrainingYes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(receivedTrainingNo))
                    .addComponent(jLabel2)
                    .addComponent(skillLabel))
                .addContainerGap(722, Short.MAX_VALUE))
        );
        jobPanelLayout.setVerticalGroup(
            jobPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jobPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jobPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(receivedTrainingYes)
                    .addComponent(receivedTrainingNo))
                .addGap(18, 18, 18)
                .addComponent(skillLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(trainingType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(161, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Training History", jobPanel);

        educationPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setText("Do you have any kind of disability ?");

        disabilityCombo.add(disabilityNo);
        disabilityNo.setText("No");
        disabilityNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disabilityNoActionPerformed(evt);
            }
        });

        disabilityCombo.add(disabilityYes);
        disabilityYes.setText("Yes");
        disabilityYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disabilityYesActionPerformed(evt);
            }
        });

        disableLabel.setText("What kind of disability do you have ?");
        disableLabel.setEnabled(false);

        disabilityType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vision", "Physical", "Speaking", "Hearing", "Other" }));
        disabilityType.setEnabled(false);

        javax.swing.GroupLayout educationPanelLayout = new javax.swing.GroupLayout(educationPanel);
        educationPanel.setLayout(educationPanelLayout);
        educationPanelLayout.setHorizontalGroup(
            educationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(educationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(educationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(educationPanelLayout.createSequentialGroup()
                        .addComponent(disabilityYes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(disabilityNo))
                    .addComponent(disableLabel)
                    .addComponent(disabilityType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(786, Short.MAX_VALUE))
        );
        educationPanelLayout.setVerticalGroup(
            educationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(educationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(educationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(disabilityYes)
                    .addComponent(disabilityNo))
                .addGap(18, 18, 18)
                .addComponent(disableLabel)
                .addGap(18, 18, 18)
                .addComponent(disabilityType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(154, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Disabilities", educationPanel);

        familyBackPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setText("What Type of family you are in: ");

        jChkNuclear.setText("Nuclear");

        chkSibHld.setText("Sibling HouseHold");

        chkSingleParent.setText("Single Parent");

        chkExtended.setText("Extended");

        javax.swing.GroupLayout familyBackPanelLayout = new javax.swing.GroupLayout(familyBackPanel);
        familyBackPanel.setLayout(familyBackPanelLayout);
        familyBackPanelLayout.setHorizontalGroup(
            familyBackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(familyBackPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jChkNuclear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkSibHld)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkSingleParent)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkExtended)
                .addContainerGap(463, Short.MAX_VALUE))
        );
        familyBackPanelLayout.setVerticalGroup(
            familyBackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(familyBackPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(familyBackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jChkNuclear)
                    .addComponent(chkSibHld)
                    .addComponent(chkSingleParent)
                    .addComponent(chkExtended))
                .addContainerGap(244, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Family Background Information", familyBackPanel);

        criminalPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setText("Select a training duration.");

        trainingDurationCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 month", "3 months", "6 months", "12 months", "Any Duration" }));

        javax.swing.GroupLayout criminalPanelLayout = new javax.swing.GroupLayout(criminalPanel);
        criminalPanel.setLayout(criminalPanelLayout);
        criminalPanelLayout.setHorizontalGroup(
            criminalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(criminalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(criminalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(trainingDurationCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(838, Short.MAX_VALUE))
        );
        criminalPanelLayout.setVerticalGroup(
            criminalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(criminalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(trainingDurationCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(223, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Training Duration", criminalPanel);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setEnabled(false);

        specificCombo.add(specificComboYes);
        specificComboYes.setText("Yes");
        specificComboYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                specificComboYesActionPerformed(evt);
            }
        });

        specificCombo.add(specificComboNo);
        specificComboNo.setText("No");
        specificComboNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                specificComboNoActionPerformed(evt);
            }
        });

        jLabel4.setText("Do you  have any specific interest in which you seek training ?");

        seekLabel.setText("Training Type:");

        trainingInterestCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Carpentry", "Security", "Construction", "Other" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(specificComboYes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(specificComboNo))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(seekLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(trainingInterestCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(specificComboYes)
                    .addComponent(specificComboNo))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seekLabel)
                    .addComponent(trainingInterestCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        jTabbedPane.addTab("Specific Interests", jPanel2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(backJBtn))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(292, 292, 292)
                                .addComponent(btnRequestJob))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(204, 204, 204)
                                .addComponent(jLabel1)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRequestJob)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backJBtn)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 997, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRequestJobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestJobActionPerformed
        // TODO add your handling code here:

        Questionnaire questionnaire = request.getQuestionaire();//business.getQuestionnaireList().addQuestionnaire();
        TrainingQuestionaire trainingQuestionaire = questionnaire.getTrainingQuestionaire() ;
        trainingQuestionaire.setTrained(receivedTrainingYes.isSelected());
        trainingQuestionaire.setDisabled(disabilityYes.isSelected());
        trainingQuestionaire.setSpecificInterest(specificComboYes.isSelected());
        if(disabilityYes.isSelected())
        {
        trainingQuestionaire.setDisability((String) disabilityType.getSelectedItem());
        }
        else if(disabilityNo.isSelected()){
            trainingQuestionaire.setDisability("None");
        }
        if(specificComboYes.isSelected()){
        trainingInterestCombo.setEnabled(true);
        trainingQuestionaire.setInterest((String) trainingInterestCombo.getSelectedItem());

        }
        else if(specificComboNo.isSelected()){
            trainingQuestionaire.setInterest("None");
        }
        trainingQuestionaire.setTrainingDuration((String) trainingDurationCombo.getSelectedItem());
        if(receivedTrainingYes.isSelected()){
              trainingQuestionaire.setTrainingField((String) trainingType.getSelectedItem());
        }
        else if(receivedTrainingNo.isSelected()){
             trainingQuestionaire.setTrainingField("None");
        }
      
        FamilyBackgroundQuestionaire FamilyBackgroundQuestionaire = questionnaire.getFamilyBackgroundQuestionaire();
        FamilyBackgroundQuestionaire.setFamilyBackground("");
        Organization org = null;
        for(Network network :business.getNetworkList()){
            if(network.getName().equalsIgnoreCase(enterprise.getNetworkName())){
                for(Enterprise et : network.getEnterpriseDirectory().getEnterpriseList()){

                    for (Organization organization : et.getOrganizationList().getOrganizationList()){

                        if (organization instanceof TrainingProcessOrganization){
                            org = organization;
                            break;
                        }

                    }
                }
            }
        }
        if (org!=null){
         
                request.setSender(userAccount);
                request.setStatus("Sent");
                request.setQuestionaire(questionnaire);
                org.getWorkQueue().getWorkRequestList().add(request);
                userAccount.getWorkQueue().getWorkRequestList().add(request);
               

        }
        JOptionPane.showMessageDialog(null, "Individual request created successfully", "Warning", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnRequestJobActionPerformed

    private void backJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJBtnActionPerformed

    private void specificComboYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_specificComboYesActionPerformed
        // TODO add your handling code here:
          seekLabel.setEnabled(true);
          trainingInterestCombo.setEnabled(true);
          
          

    }//GEN-LAST:event_specificComboYesActionPerformed

    private void specificComboNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_specificComboNoActionPerformed
        // TODO add your handling code here:
             seekLabel.setEnabled(false);

    }//GEN-LAST:event_specificComboNoActionPerformed

    private void disabilityYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disabilityYesActionPerformed
        // TODO add your handling code here:
         disabilityType.setEnabled(true);
            disableLabel.setEnabled(true);
    }//GEN-LAST:event_disabilityYesActionPerformed

    private void disabilityNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disabilityNoActionPerformed
        // TODO add your handling code here:
         disabilityType.setEnabled(false);
            disableLabel.setEnabled(false);
    }//GEN-LAST:event_disabilityNoActionPerformed

    private void receivedTrainingYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receivedTrainingYesActionPerformed
        // TODO add your handling code here:
         skillLabel.setEnabled(true);
            trainingType.setEnabled(true);
    }//GEN-LAST:event_receivedTrainingYesActionPerformed

    private void receivedTrainingNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receivedTrainingNoActionPerformed
  skillLabel.setEnabled(false);
            trainingType.setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_receivedTrainingNoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJBtn;
    private javax.swing.JButton btnRequestJob;
    private javax.swing.JCheckBox chkExtended;
    private javax.swing.JCheckBox chkSibHld;
    private javax.swing.JCheckBox chkSingleParent;
    private javax.swing.JPanel criminalPanel;
    private javax.swing.ButtonGroup disabilityCombo;
    private javax.swing.JRadioButton disabilityNo;
    private javax.swing.JComboBox<String> disabilityType;
    private javax.swing.JRadioButton disabilityYes;
    private javax.swing.JLabel disableLabel;
    private javax.swing.JPanel educationPanel;
    private javax.swing.JPanel familyBackPanel;
    private javax.swing.JCheckBox jChkNuclear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JPanel jobPanel;
    private javax.swing.JRadioButton receivedTrainingNo;
    private javax.swing.JRadioButton receivedTrainingYes;
    private javax.swing.JLabel seekLabel;
    private javax.swing.JLabel skillLabel;
    private javax.swing.ButtonGroup specificCombo;
    private javax.swing.JRadioButton specificComboNo;
    private javax.swing.JRadioButton specificComboYes;
    private javax.swing.ButtonGroup trainingCombo;
    private javax.swing.JComboBox<String> trainingDurationCombo;
    private javax.swing.JComboBox<String> trainingInterestCombo;
    private javax.swing.JComboBox<String> trainingType;
    // End of variables declaration//GEN-END:variables
}
