/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CuratorOrganization.JobManagerRole;

import Business.EcoSystem;
import Business.Enterpise.Enterprise;
import Business.Network.Network;
import Business.Organization.JobProcessOrganization;
import Business.Organization.JobRequestManagerOrganization;
import Business.Organization.Organization;
import Business.Questionnaire.CriminalRelatedQuestionaire;
import Business.Questionnaire.DrugAbuseQuestionaire;
import Business.Questionnaire.EducationQuestionaire;
import Business.Questionnaire.FamilyBackgroundQuestionaire;
import Business.Questionnaire.JobQuestionaire;
import Business.Questionnaire.Questionnaire;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.JobWorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author sanch
 */
public class AddJobRequestDetailsJPanel extends javax.swing.JPanel {
private JPanel userProcessContainer;
    private JobRequestManagerOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    EcoSystem business;
    JobWorkRequest request;
    /**
     * Creates new form ManageJobRequestDetailsJPanel
     */
    public AddJobRequestDetailsJPanel() {
        initComponents();
    }

    AddJobRequestDetailsJPanel(JPanel userProcessContainer, UserAccount userAccount, JobRequestManagerOrganization organization, Enterprise enterprise, EcoSystem business,JobWorkRequest workrequest) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization =(JobRequestManagerOrganization) organization;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        this.business = business;
        this.request = workrequest;
        populateWorkRequestData();
//throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupRead = new javax.swing.ButtonGroup();
        buttonGroupWrite = new javax.swing.ButtonGroup();
        buttonGroupCrime = new javax.swing.ButtonGroup();
        buttonGroupDrugs = new javax.swing.ButtonGroup();
        buttonGroupCommDrugs = new javax.swing.ButtonGroup();
        buttonGroupComp = new javax.swing.ButtonGroup();
        buttonGroupFamily = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        btnRequestJob = new javax.swing.JButton();
        backJBtn = new javax.swing.JButton();
        jTabbedPane = new javax.swing.JTabbedPane();
        jobPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        rbComputerNo = new javax.swing.JRadioButton();
        rbComputerYes = new javax.swing.JRadioButton();
        educationPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        rbReadNo = new javax.swing.JRadioButton();
        rbReadYes = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        rbWriteNo = new javax.swing.JRadioButton();
        rbWriteYes = new javax.swing.JRadioButton();
        familyBackPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        rbNuclear = new javax.swing.JRadioButton();
        rbSibling = new javax.swing.JRadioButton();
        rbSingleParent = new javax.swing.JRadioButton();
        rbExtended = new javax.swing.JRadioButton();
        criminalPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        rbConvictedNo = new javax.swing.JRadioButton();
        rbConvictedYes = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        rbDrugsYes = new javax.swing.JRadioButton();
        rbDrugsNo = new javax.swing.JRadioButton();
        rbChkDrugCommNo = new javax.swing.JRadioButton();
        rbChkDrugCommYes = new javax.swing.JRadioButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Lucida Bright", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Enter Individual job Details");

        btnRequestJob.setBackground(new java.awt.Color(102, 255, 51));
        btnRequestJob.setText("Request Job");
        btnRequestJob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestJobActionPerformed(evt);
            }
        });

        backJBtn.setBackground(new java.awt.Color(255, 0, 0));
        backJBtn.setText("<< Back");
        backJBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJBtnActionPerformed(evt);
            }
        });

        jobPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Can you use computer?");

        buttonGroupComp.add(rbComputerNo);
        rbComputerNo.setText("No");

        buttonGroupComp.add(rbComputerYes);
        rbComputerYes.setText("Yes");

        javax.swing.GroupLayout jobPanelLayout = new javax.swing.GroupLayout(jobPanel);
        jobPanel.setLayout(jobPanelLayout);
        jobPanelLayout.setHorizontalGroup(
            jobPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jobPanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jobPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jobPanelLayout.createSequentialGroup()
                        .addComponent(rbComputerYes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbComputerNo))
                    .addComponent(jLabel2))
                .addContainerGap(576, Short.MAX_VALUE))
        );
        jobPanelLayout.setVerticalGroup(
            jobPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jobPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jobPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbComputerYes)
                    .addComponent(rbComputerNo))
<<<<<<< HEAD
                .addContainerGap(171, Short.MAX_VALUE))
=======
                .addContainerGap(115, Short.MAX_VALUE))
>>>>>>> c7bb0e14c612ed5da0c2fb03c6f347dddce98ffc
        );

        jTabbedPane.addTab("Job Information", jobPanel);

        educationPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setText("Can you read?");

        buttonGroupRead.add(rbReadNo);
        rbReadNo.setText("No");

        buttonGroupRead.add(rbReadYes);
        rbReadYes.setText("Yes");

        jLabel8.setText("Can you write?");

        buttonGroupWrite.add(rbWriteNo);
        rbWriteNo.setText("No");

        buttonGroupWrite.add(rbWriteYes);
        rbWriteYes.setText("Yes");

        javax.swing.GroupLayout educationPanelLayout = new javax.swing.GroupLayout(educationPanel);
        educationPanel.setLayout(educationPanelLayout);
        educationPanelLayout.setHorizontalGroup(
            educationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(educationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(educationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(educationPanelLayout.createSequentialGroup()
                        .addComponent(rbWriteYes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbWriteNo))
                    .addComponent(jLabel7)
                    .addGroup(educationPanelLayout.createSequentialGroup()
                        .addComponent(rbReadYes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbReadNo)))
                .addContainerGap(634, Short.MAX_VALUE))
        );
        educationPanelLayout.setVerticalGroup(
            educationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(educationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(educationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbReadYes)
                    .addComponent(rbReadNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(educationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbWriteYes)
                    .addComponent(rbWriteNo))
<<<<<<< HEAD
                .addContainerGap(130, Short.MAX_VALUE))
=======
                .addContainerGap(74, Short.MAX_VALUE))
>>>>>>> c7bb0e14c612ed5da0c2fb03c6f347dddce98ffc
        );

        jTabbedPane.addTab("Education Information", educationPanel);

        familyBackPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setText("What Type of family you are in: ");

        buttonGroupFamily.add(rbNuclear);
        rbNuclear.setText("Nuclear");

        buttonGroupComp.add(rbSibling);
        rbSibling.setText("Sibling HouseHold");

        buttonGroupComp.add(rbSingleParent);
        rbSingleParent.setText("Single Parent");

        buttonGroupComp.add(rbExtended);
        rbExtended.setText("Extended");

        javax.swing.GroupLayout familyBackPanelLayout = new javax.swing.GroupLayout(familyBackPanel);
        familyBackPanel.setLayout(familyBackPanelLayout);
        familyBackPanelLayout.setHorizontalGroup(
            familyBackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(familyBackPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbNuclear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbSibling)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbSingleParent)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
<<<<<<< HEAD
                .addComponent(chkExtended)
                .addContainerGap(217, Short.MAX_VALUE))
=======
                .addComponent(rbExtended)
                .addContainerGap(188, Short.MAX_VALUE))
>>>>>>> c7bb0e14c612ed5da0c2fb03c6f347dddce98ffc
        );
        familyBackPanelLayout.setVerticalGroup(
            familyBackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(familyBackPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(familyBackPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
<<<<<<< HEAD
                    .addComponent(jChkNuclear)
                    .addComponent(chkSibHld)
                    .addComponent(chkSingleParent)
                    .addComponent(chkExtended))
                .addContainerGap(191, Short.MAX_VALUE))
=======
                    .addComponent(rbNuclear)
                    .addComponent(rbSibling)
                    .addComponent(rbSingleParent)
                    .addComponent(rbExtended))
                .addContainerGap(135, Short.MAX_VALUE))
>>>>>>> c7bb0e14c612ed5da0c2fb03c6f347dddce98ffc
        );

        jTabbedPane.addTab("Family Background Information", familyBackPanel);

        criminalPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setText("Do you ever convicted for a crime:");

        buttonGroupCrime.add(rbConvictedNo);
        rbConvictedNo.setText("No");

        buttonGroupCrime.add(rbConvictedYes);
        rbConvictedYes.setText("Yes");

        javax.swing.GroupLayout criminalPanelLayout = new javax.swing.GroupLayout(criminalPanel);
        criminalPanel.setLayout(criminalPanelLayout);
        criminalPanelLayout.setHorizontalGroup(
            criminalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(criminalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(criminalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(criminalPanelLayout.createSequentialGroup()
                        .addComponent(rbConvictedYes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbConvictedNo)))
                .addContainerGap(550, Short.MAX_VALUE))
        );
        criminalPanelLayout.setVerticalGroup(
            criminalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(criminalPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(criminalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbConvictedYes)
                    .addComponent(rbConvictedNo))
<<<<<<< HEAD
                .addContainerGap(171, Short.MAX_VALUE))
=======
                .addContainerGap(115, Short.MAX_VALUE))
>>>>>>> c7bb0e14c612ed5da0c2fb03c6f347dddce98ffc
        );

        jTabbedPane.addTab("Criminal Information", criminalPanel);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setText("Do you use drugs:");

        jLabel5.setText("Do you know atleast one teenager of your community that uses drugs?");

        buttonGroupDrugs.add(rbDrugsYes);
        rbDrugsYes.setText("Yes");

        buttonGroupDrugs.add(rbDrugsNo);
        rbDrugsNo.setText("No");

        buttonGroupCommDrugs.add(rbChkDrugCommNo);
        rbChkDrugCommNo.setText("No");

        buttonGroupCommDrugs.add(rbChkDrugCommYes);
        rbChkDrugCommYes.setText("Yes");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rbChkDrugCommYes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rbChkDrugCommNo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rbDrugsYes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbDrugsNo)))
                .addContainerGap(375, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbDrugsYes)
                    .addComponent(rbDrugsNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbChkDrugCommYes)
                    .addComponent(rbChkDrugCommNo))
<<<<<<< HEAD
                .addContainerGap(125, Short.MAX_VALUE))
=======
                .addContainerGap(69, Short.MAX_VALUE))
>>>>>>> c7bb0e14c612ed5da0c2fb03c6f347dddce98ffc
        );

        jTabbedPane.addTab("DrugAbuse Information", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(backJBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(230, 230, 230)
                                .addComponent(jLabel1)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnRequestJob)
                .addGap(158, 158, 158))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnRequestJob)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(backJBtn)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    private void populateWorkRequestData(){
        Questionnaire questionaire = request.getQuestionaire();
        if(questionaire.isIsDetailsSet()){
        rbComputerYes.setSelected(questionaire.getJobQuestionaire().isIsComputer());
        rbReadYes.setSelected(questionaire.getEducationQuestionaire().isIsRead());
        rbWriteYes.setSelected(questionaire.getEducationQuestionaire().isIsWrite());
        rbConvictedYes.setSelected(questionaire.getCriminalRelatedQuestionaire().isIsConvCrime());
        rbDrugsYes.setSelected(questionaire.getDrugAbuseQuestionaire().isIsConsumeDrug());
        rbChkDrugCommYes.setSelected(questionaire.getDrugAbuseQuestionaire().isIsComDrug());
        rbComputerNo.setSelected(!questionaire.getJobQuestionaire().isIsComputer());
        rbReadNo.setSelected(!questionaire.getEducationQuestionaire().isIsRead());
        rbWriteNo.setSelected(!questionaire.getEducationQuestionaire().isIsWrite());
        rbConvictedNo.setSelected(!questionaire.getCriminalRelatedQuestionaire().isIsConvCrime());
        rbDrugsNo.setSelected(!questionaire.getDrugAbuseQuestionaire().isIsConsumeDrug());
        rbChkDrugCommNo.setSelected(!questionaire.getDrugAbuseQuestionaire().isIsComDrug());
        String str =questionaire.getFamilyBackgroundQuestionaire().getFamilyBackground();
        if(str != null && str.equalsIgnoreCase("Nuclear"))
        {
            rbNuclear.setSelected(true);
        }
        else if(str != null && str.equalsIgnoreCase("Sibling"))
        {
            rbSibling.setSelected(true);
        } 
        else if(str != null && str.equalsIgnoreCase("Extended"))
        {
            rbExtended.setSelected(true);
        } 
        else if(str != null && str.equalsIgnoreCase("SingleParent"))
        {
            rbSingleParent.setSelected(true);
        }
        }
    }
    private void btnRequestJobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestJobActionPerformed
        // TODO add your handling code here:
       
        Questionnaire questionnaire = request.getQuestionaire();//business.getQuestionnaireList().addQuestionnaire();
        questionnaire.setIsDetailsSet(true);
        JobQuestionaire jobQuestionaire = questionnaire.getJobQuestionaire() ;
        jobQuestionaire.setIsComputer(rbComputerYes.isSelected());
        
        EducationQuestionaire  EducationQuestionaire = questionnaire.getEducationQuestionaire();
        EducationQuestionaire.setIsRead(rbReadYes.isSelected());
        EducationQuestionaire.setIsWrite(rbWriteYes.isSelected());
        
        FamilyBackgroundQuestionaire FamilyBackgroundQuestionaire = questionnaire.getFamilyBackgroundQuestionaire();
        String strfamily="";
        if(rbNuclear.isSelected()){
        strfamily = rbNuclear.isSelected() ? "Nuclear" : "";
        }
        else if (rbSibling.isSelected()){
            strfamily = rbSibling.isSelected() ? "Sibling" : "";
        }
        else if (rbExtended.isSelected()){
            strfamily = rbExtended.isSelected() ? "Extended" : "";
        }
        else if (rbSingleParent.isSelected()){
            strfamily = rbSingleParent.isSelected() ? "SingleParent" : "";
        }
        FamilyBackgroundQuestionaire.setFamilyBackground(strfamily);
        
        CriminalRelatedQuestionaire CriminalRelatedQuestionaire=questionnaire.getCriminalRelatedQuestionaire();
        CriminalRelatedQuestionaire.setIsConvCrime(rbConvictedYes.isSelected());
        
        DrugAbuseQuestionaire DrugAbuseQuestionaire = questionnaire.getDrugAbuseQuestionaire();
        DrugAbuseQuestionaire.setIsConsumeDrug(rbDrugsYes.isSelected());
        DrugAbuseQuestionaire.setIsComDrug(rbChkDrugCommYes.isSelected());
        //CriminalRelatedQuestionaire.set
        //jobQuestionaire.setIsWrite(true);
        //jobQuestionaire.setBasicKnowledge("Computer");
        Organization org = null;
        for(Network network :business.getNetworkList()){
            if(network.getName().equalsIgnoreCase(enterprise.getNetworkName())){
                for(Enterprise et : network.getEnterpriseDirectory().getEnterpriseList()){

                    for (Organization organization : et.getOrganizationList().getOrganizationList()){
                        
                            if (organization instanceof JobProcessOrganization){
                                org = organization;
                                break;
                            }
                        
                        
                    }
                }   
            }
        }
        if (org!=null){
            //if(requestType.equalsIgnoreCase("job")){
            //    JobWorkRequest request = new JobWorkRequest();
                request.setSender(userAccount);
                request.setStatus("Sent");
                request.setQuestionaire(questionnaire);
                org.getWorkQueue().getWorkRequestList().add(request);
                userAccount.getWorkQueue().getWorkRequestList().add(request);
            //}
//            else if(requestType.equalsIgnoreCase("edu")){
//                TrainingRequest request = new TrainingRequest();
//                request.setSender(userAccount);
//                request.setStatus("Sent");
//                request.setQuestionaire(questionnaire);
//                org.getWorkQueue().getWorkRequestList().add(request);
//                userAccount.getWorkQueue().getWorkRequestList().add(request);
//            }

        }
        JOptionPane.showMessageDialog(null, "Individual request created successfully", "Warning", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_btnRequestJobActionPerformed

    private void backJBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJBtn;
    private javax.swing.JButton btnRequestJob;
    private javax.swing.ButtonGroup buttonGroupCommDrugs;
    private javax.swing.ButtonGroup buttonGroupComp;
    private javax.swing.ButtonGroup buttonGroupCrime;
    private javax.swing.ButtonGroup buttonGroupDrugs;
    private javax.swing.ButtonGroup buttonGroupFamily;
    private javax.swing.ButtonGroup buttonGroupRead;
    private javax.swing.ButtonGroup buttonGroupWrite;
    private javax.swing.JPanel criminalPanel;
    private javax.swing.JPanel educationPanel;
    private javax.swing.JPanel familyBackPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JPanel jobPanel;
    private javax.swing.JRadioButton rbChkDrugCommNo;
    private javax.swing.JRadioButton rbChkDrugCommYes;
    private javax.swing.JRadioButton rbComputerNo;
    private javax.swing.JRadioButton rbComputerYes;
    private javax.swing.JRadioButton rbConvictedNo;
    private javax.swing.JRadioButton rbConvictedYes;
    private javax.swing.JRadioButton rbDrugsNo;
    private javax.swing.JRadioButton rbDrugsYes;
    private javax.swing.JRadioButton rbExtended;
    private javax.swing.JRadioButton rbNuclear;
    private javax.swing.JRadioButton rbReadNo;
    private javax.swing.JRadioButton rbReadYes;
    private javax.swing.JRadioButton rbSibling;
    private javax.swing.JRadioButton rbSingleParent;
    private javax.swing.JRadioButton rbWriteNo;
    private javax.swing.JRadioButton rbWriteYes;
    // End of variables declaration//GEN-END:variables
}
